# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm # Utilisez 'orm' si vous utilisez Doctrine ORM

    mappings:
        book_image: # Nom de votre mapping (peut être personnalisé)
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer